version: "3"
services:
  frontend:
    depends_on:
      - truelayer-service
      - lunch-money-service
    build:
      context: ../../frontend
      args:
        REACT_APP_TRUELAYER_SERVICE_ORIGIN: http://localhost:8080
    image: lunchmoneysync/frontend
    ports:
      - 8000:80
    restart: always

  truelayer-service:
    depends_on:
      - mongo
      - kafka
    build:
      context: ../../backend/truelayer-service
    image: lunchmoneysync/truelayer-service
    environment:
      TRUELAYER_CLIENT_ID: $TRUELAYER_CLIENT_ID
      TRUELAYER_CLIENT_SECRET: $TRUELAYER_CLIENT_SECRET
      TRUELAYER_REDIRECT_URI: $TRUELAYER_REDIRECT_URI
      TRUELAYER_STATE_SECRET: $TRUELAYER_STATE_SECRET
      TRUELAYER_TOKEN_ENCRYPTION_SECRET: $TRUELAYER_TOKEN_ENCRYPTION_SECRET
      TRUELAYER_TOKEN_ENCRYPTION_SALT: $TRUELAYER_TOKEN_ENCRYPTION_SALT
      TRUELAYER_USE_SANDBOX: $TRUELAYER_USE_SANDBOX
    ports:
      - 8080:8080
    restart: always

  lunch-money-service:
    depends_on:
      - mongo
      - kafka
    build:
      context: ../../backend/lunch-money-service
    image: lunchmoneysync/lunch-money-service
    environment:
      LUNCH_MONEY_ACCESS_TOKEN: $LUNCH_MONEY_ACCESS_TOKEN
    ports:
      - 8081:8081
    restart: always

  mongo:
    image: mongo:4.4.18
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin-user
      MONGO_INITDB_ROOT_PASSWORD: admin-pass
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./init/mongo/users.js:/docker-entrypoint-initdb.d/users.js:ro
      - ./data/mongo/db:/data/db
    ports:
      - 27017:27017
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./data/zookeeper/data:/var/lib/zookeeper/data
      - ./data/zookeeper/log:/var/lib/zookeeper/log
    ports:
      - 2181:2181
    restart: always

  kafka:
    image: confluentinc/cp-kafka:7.4.3
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka/data:/var/lib/kafka/data
    ports:
      - 29092:29092
    restart: always
